### ISSUE TITLE
Error when updating with Flutter2 (media_query nullOK)

### ISSUE THREAD

**Issue by fvisticot** [fluttercandies/extended_image#311]
Using extended_image-1.6.0 from native_pdf_view

`../.pub-cache/hosted/pub.dartlang.org/extended_image-1.6.0/lib/src/extended_image.dart:785:44: Error: No named parameter with the name 'nullOk'. _invertColors = MediaQuery.of(context, nullOk: true)?.invertColors ?? ^^^^^^ ../development/flutter/packages/flutter/lib/src/widgets/media_query.dart:818:25: Context: Found this candidate, but the arguments don't match. static MediaQueryData of(BuildContext context) {`

**Comment by samandmoore** [comment]
this will end up getting fixed here probably https://github.com/fluttercandies/extended_image/pull/302

but, i'd love to open a PR and get a release out that supports flutter 2 without needing to wait for the NNBD migration here as well. i'm happy to open a PR with the one-line fix for this if someone would be able to release it. gotta get this fixed so we can get `native_pdf_view` fixed https://github.com/rbcprolabs/packages.flutter/issues/166 so that we can upgrade to flutter 2.

**Comment by dahutiger** [comment]
同样的问题

**Comment by zmtzawqlp** [comment]
3.0.0 is ready on pub.dev
