### ISSUE TITLE
Network Image blinks every time the setStest is called

### ISSUE THREAD

**Issue by umbertogrimaldi** [fluttercandies/extended_image#355]
Hi guys, 
I noticed that every time I perform a setState (or the view is going to update itself such as when you show modalBottomSheet) the image blinks (like it's loading again). Any fix for this?

**Comment by zmtzawqlp** [comment]
setState at the smallest area will better

**Comment by umbertogrimaldi** [comment]
What do you mean by the smallest area? Anyway I can't control the ui updates on methods such as showModalBottomSheet

**Comment by zmtzawqlp** [comment]
i guess your image is big. no matter which Image Widget you use, it always reload. try reduce your image size first

**Comment by frankyvij** [comment]
Hello @zmtzawqlp , actually that is not true. I was looking to replace flutter_advanced_networkimage
 and during initial testing with this package, I also noticed the same thing. I never experienced this problem with flutter_advanced_networkimage.

Is it because you are trying to go to network before checking cache everytime setState is called?

@umbertogrimaldi : Do you have any solution to this problem?

**Comment by frankyvij** [comment]
Ok it seems if I set gaplessPlayback to true, it does not blink anymore. But I don't know what gaplessPlayback is originally intended for.

**Comment by zmtzawqlp** [comment]
https://github.com/flutter/flutter/blob/03a3e7b1e416ecf7ad3399e2fe2e161aa4c336e5/packages/flutter/lib/src/widgets/image.dart#L1043

**Comment by zmtzawqlp** [comment]
``` dart
    if (!widget.gaplessPlayback || rebuild) {      setState(() {        _replaceImage(info: null);        _loadState = LoadState.loading;      });    }
``` 
ExtendedImage set LoadState.loading at that moment, so you will enter loading at first time then show image.
