### ISSUE TITLE
Not compatible with Flutter 3.11.x

### ISSUE THREAD

**Issue by mark8044** [fluttercandies/extended_image#581]
### Version

8.0.1

### Platforms

dart

### Device Model

All

### flutter info

```sh
It looks like this is incompatible with 3.11.x Beta channel.  I have a feeling 3.11 will goto stable rather quickly since it has some important fixes to 3.10 that will need to be pushed out
```

### How to reproduce?

Run application with 3.11 Flutter

**Comment by zmtzawqlp** [comment]
only support stable

**Comment by gslender** [comment]
That's not true, as stable has the API marked as deprecated and so the library is not currently using supported API, that's why it doesn't work with the the beta channels. This package maintainer isn't supporting the stable channel correctly and is not making it easier for developers who rely on it. I'm thinking I might create and publish a fork that is correctly supporting stable. Thoughts?

**Comment by zmtzawqlp** [comment]
> That's not true, as stable has the API marked as deprecated and so the library is not currently using supported API, that's why it doesn't work with the the beta channels. This package maintainer isn't supporting the stable channel correctly and is not making it easier for developers who rely on it. I'm thinking I might create and publish a fork that is correctly supporting stable. Thoughts?

It's happy to hear that. But we will never know the finnal result of deprecated api before it had removed. Flutter team always change api frequently in beta/ master branch and also roll back them. It's kind of you can maintenance it base on beta or master branch if you have a time.

**Comment by gslender** [comment]
The code in painting.dart of extended_image is using a workaround fix that was introduced by the flutter team (and copied by you) that has now been deprecated. The reason your code breaks in beta is that the code you're relying on was only implemented to solve a problem with performance that has since been fixed and reverted. Again, it is a shame you can't take a moment to look ahead rather than racing around on the day that Beta turns into Stable, and the entire package breaks countless apps as a result of not being compatible with the upcoming API. Looks like a fork is the only way I can continue to use this package.

**Comment by zmtzawqlp** [comment]
> The code in painting.dart of extended_image is using a workaround fix that was introduced by the flutter team (and copied by you) that has now been deprecated. The reason your code breaks in beta is that the code you're relying on was only implemented to solve a problem with performance that has since been fixed and reverted. Again, it is a shame you can't take a moment to look ahead rather than racing around on the day that Beta turns into Stable, and the entire package breaks countless apps as a result of not being compatible with the upcoming API. Looks like a fork is the only way I can continue to use this package.

We are delighted to see more people joining the Flutter open-source community and contributing to its maintenance. We eagerly anticipate your future open-source projects.

**Comment by yangcheng** [comment]
> The code in painting.dart of extended_image is using a workaround fix that was introduced by the flutter team (and copied by you) that has now been deprecated. The reason your code breaks in beta is that the code you're relying on was only implemented to solve a problem with performance that has since been fixed and reverted. Again, it is a shame you can't take a moment to look ahead rather than racing around on the day that Beta turns into Stable, and the entire package breaks countless apps as a result of not being compatible with the upcoming API. Looks like a fork is the only way I can continue to use this package.

we are experience similar issue, have you created a fork already?

**Comment by gslender** [comment]
Yes, use this... it works with Flutter Beta 3.11

```
dependency_overrides:
  extended_image:
    git:
      url: https://github.com/gslender/extended_image
      ref: support-flutter-beta-3.11      
```

**Comment by zmtzawqlp** [comment]
8.1.0 is ready
